export const environment = {
  tokenApi: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlRodSBEZWMgMDcgMjAyMyAwNDo0NzozOSBHTVQrMDAwMC43YnJ1bm84QGdtYWlsLmNvbSIsImlhdCI6MTcwMTkyNDQ1OX0.fcro7c2XTP4CXJ--QCDoFtkscNq03zXsAZbDwtX_kCs"
};
